// In-memory prototype state. Resets on every server restart — that's
// the intended behavior for a demo running on Railway.
//
// Domain: Tropigas employees report IT issues to UCG's Mesa de Ayuda.
// Most real incidents are Salesforce ↔ EMAS interface errors that
// affect specific end customers (RO4822, CY2526, RO1858, etc.).
// The ticket schema captures both the IT issue AND, when applicable,
// the affected customer (EMAS#, ship-to, contact info).

function createInitialState() {
  const now = Date.now();
  const min = (m) => new Date(now - m * 60_000).toISOString();
  const hr  = (h) => min(h * 60);
  const day = (d) => min(d * 1440);

  const users = [
    // ----- Empleados Tropigas (admin role) -----
    { id: 'EMP-2104', name: 'M. Ríos',  initials: 'MR', role: 'admin', email: 'm.rios@tropigas.pr',  department: 'Administración', sucursal: 'Bayamón · Oficina Central', ext: 'x4521', supervisor: 'L. Vega',     asset: 'LT-BYM-0114' },
    { id: 'EMP-1981', name: 'A. Cruz',  initials: 'AC', role: 'admin', email: 'a.cruz@tropigas.pr',  department: 'Operaciones',    sucursal: 'Caguas',                    ext: 'x3204', supervisor: 'R. Mejía',    asset: 'LT-CAG-0091' },
    { id: 'EMP-1755', name: 'D. Soto',  initials: 'DS', role: 'admin', email: 'd.soto@tropigas.pr',  department: 'Finanzas',       sucursal: 'Ponce',                     ext: 'x5102', supervisor: 'C. Aponte',   asset: 'LT-PCE-0044' },
    { id: 'EMP-2098', name: 'P. Rivas', initials: 'PR', role: 'admin', email: 'p.rivas@tropigas.pr', department: 'RRHH',           sucursal: 'Mayagüez',                  ext: 'x6018', supervisor: 'M. Báez',     asset: 'LT-MAG-0019' },
    { id: 'EMP-1881', name: 'R. Lozada', initials: 'RL', role: 'admin', email: 'r.lozada@tropigas.pr', department: 'Ventas',       sucursal: 'Bayamón · Oficina Central', ext: 'x4533', supervisor: 'L. Vega',     asset: 'LT-BYM-0124' },
    { id: 'EMP-2042', name: 'E. Núñez',  initials: 'EN', role: 'admin', email: 'e.nunez@tropigas.pr', department: 'Logística',     sucursal: 'Caguas',                    ext: 'x3211', supervisor: 'R. Mejía',    asset: 'LT-CAG-0098' },

    // ----- UCG IT team (it role) -----
    { id: 'UCG-IT-007', name: 'J. Marrero', initials: 'JM', role: 'it', email: 'j.marrero@ucg.pr', team: 'IT Support · Tier 2', sucursal: 'UCG · San Juan', ext: 'x2104', supervisor: 'A. Vega · Director IT' },
    { id: 'UCG-IT-014', name: 'R. Quiles',  initials: 'RQ', role: 'it', email: 'r.quiles@ucg.pr',  team: 'IT Support · Tier 2', sucursal: 'UCG · San Juan', ext: 'x2108', supervisor: 'A. Vega · Director IT' },
    { id: 'UCG-IT-021', name: 'L. Rivera',  initials: 'LR', role: 'it', email: 'l.rivera@ucg.pr',  team: 'IT Support · Tier 1', sucursal: 'UCG · San Juan', ext: 'x2112', supervisor: 'A. Vega · Director IT' },
    { id: 'UCG-IT-009', name: 'C. Méndez',  initials: 'CM', role: 'it', email: 'c.mendez@ucg.pr',  team: 'IT Support · Tier 1', sucursal: 'UCG · San Juan', ext: 'x2115', supervisor: 'A. Vega · Director IT' },
    { id: 'UCG-IT-018', name: 'A. Torres',  initials: 'AT', role: 'it', email: 'a.torres@ucg.pr',  team: 'IT Support · Tier 1', sucursal: 'UCG · San Juan', ext: 'x2118', supervisor: 'A. Vega · Director IT' },
    { id: 'UCG-IT-027', name: 'D. Vázquez', initials: 'DV', role: 'it', email: 'd.vazquez@ucg.pr', team: 'IT Support · Tier 2', sucursal: 'UCG · San Juan', ext: 'x2121', supervisor: 'A. Vega · Director IT' },
  ];

  function slaFor(importance) {
    return importance === 'Alta' ? 4 : importance === 'Media' ? 8 : 24;
  }

  // Real customers from the Salesforce ↔ EMAS interface log
  const sampleClientes = {
    'RO4822': { emasNumber: 'RO4822', salesforceId: '001TQ000007RKaSYAW', accountType: 'Comercial', name: 'Restaurante La Cima', contactName: 'M. Vega',    phone: '787-555-0142', email: 'm.vega@lacima.pr',     shipTo: '00 — Carr. 2 km 45.8, Hatillo, PR 00659',          mailingAddress: 'PO Box 1245, Hatillo, PR 00659' },
    'CY2526': { emasNumber: 'CY2526', salesforceId: '001TQ00000kGWSrYAO', accountType: 'Comercial', name: 'Cafetería Yauco',     contactName: 'J. Padilla', phone: '787-555-0387', email: 'cafeteriayauco@gmail.com', shipTo: 'Calle Comercio 18, Yauco, PR 00698',                mailingAddress: 'Calle Comercio 18, Yauco, PR 00698' },
    'RO1858': { emasNumber: 'RO1858', salesforceId: '0013t00001zftHPAAY', accountType: 'Comercial', name: 'Panadería El Trigo', contactName: 'L. Reyes',   phone: '787-555-0271', email: 'l.reyes@eltrigo.pr',     shipTo: '01 — Ave. Roosevelt 540, San Juan, PR 00917',      mailingAddress: 'PO Box 2014, San Juan, PR 00919' },
    'RO3852': { emasNumber: 'RO3852', salesforceId: '001TQ00000SFKskYAH', accountType: 'Comercial', name: 'Hotel Costa Sol',    contactName: 'P. Sánchez', phone: '787-555-0509', email: 'p.sanchez@costasol.pr',  shipTo: '00 — Carr. 901 km 1.4, Maunabo, PR 00707',         mailingAddress: 'PO Box 88, Maunabo, PR 00707' },
    'NOEMAS': { emasNumber: null,    salesforceId: '001TQ00000qHlnqYAC', accountType: 'Individual', name: 'Carlos Méndez',       contactName: 'Carlos Méndez', phone: '787-555-0610', email: 'cmendez1985@yahoo.com', shipTo: 'Calle 12 #18, Urb. Villa Caparra, Guaynabo, PR 00969', mailingAddress: 'Calle 12 #18, Urb. Villa Caparra, Guaynabo, PR 00969' },
  };

  const tickets = [
    // ===== Real Salesforce ↔ EMAS interface incidents (from the Log) =====
    {
      id: 'SM-00043',
      summary: 'Customer ID mismatch · RO4822 · 8 ocurrencias en 13 días',
      description: 'La interfaz Salesforce → EMAS rechaza repetidamente las transacciones del cliente RO4822 (Restaurante La Cima). El error indica que el Salesforce Customer ID no coincide con el EMAS Customer Number. Bloqueando facturación recurrente.',
      empleadoId: 'EMP-2104',
      categoria: 'Sistema',
      importance: 'Alta',
      status: 'En progreso',
      assigneeId: 'UCG-IT-007',
      slaHours: slaFor('Alta'),
      assetId: null,
      tags: ['salesforce', 'emas-interface', 'recurrente', 'customer-id-mismatch'],
      createdAt: day(13),
      updatedAt: hr(2),
      cliente: sampleClientes['RO4822'],
      salesforceTxIds: ['3729', '3730', '3734'],
      errorMessage: 'Salesforce Customer ID is "001TQ000007RKaSYAW", Shipto ID is "a03TQ00000ch4aQYAQ". Salesforce indicates it is EMAS Customer Number "RO4822", Ship-To "XX". ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match',
      recurrenceCount: 8,
      firstOccurrence: day(13),
      lastOccurrence: hr(8),
      relatedKb: ['KB-029'],
      comments: [
        { author: 'M. Ríos',    authorId: 'EMP-2104',   role: 'empleado', type: 'message', body: 'El cliente RO4822 (Restaurante La Cima) no procesa transacciones desde el 1 de abril. Salesforce manda el error de Customer ID mismatch repetidamente. Ya van 8 transacciones bloqueadas y el cliente está esperando facturación.', createdAt: day(13) },
        { author: 'J. Marrero', authorId: 'UCG-IT-007', role: 'it',       type: 'note',    body: 'Confirmado en log de interfaz. SF Customer 001TQ000007RKaSYAW está mapeado a EMAS RO4822 con Ship-To "XX" en SF, pero EMAS espera Ship-To "00". Probablemente faltó migrar el ship-to o se duplicó el registro. Investigando con DBA.', createdAt: day(12) },
        { author: 'J. Marrero', authorId: 'UCG-IT-007', role: 'it',       type: 'message', body: 'Hola M., estoy revisando el mapeo de Ship-To del cliente RO4822 con el equipo de DB. Te aviso al cierre del día. Puedes redirigir las transacciones nuevas al backup-queue mientras tanto.', createdAt: day(12) },
        { author: 'sistema',    authorId: null,         role: 'system',   type: 'system',  body: 'Ocurrencia #5 detectada · TX 3729 · 2026-04-08', createdAt: day(7) },
        { author: 'sistema',    authorId: null,         role: 'system',   type: 'system',  body: 'Ocurrencia #6 detectada · TX 3730 · 2026-04-08', createdAt: day(7) },
        { author: 'sistema',    authorId: null,         role: 'system',   type: 'system',  body: 'Ocurrencia #8 detectada · TX 3734 · 2026-05-04', createdAt: hr(8) },
      ],
    },
    {
      id: 'SM-00044',
      summary: 'Customer ID mismatch · CY2526 · 6 ocurrencias',
      description: 'Cliente CY2526 (Cafetería Yauco) no entra al sistema. Salesforce indica EMAS Customer Number CY2526 pero la interfaz lo rechaza con error de mismatch. Sin Ship-To en SF.',
      empleadoId: 'EMP-2098',
      categoria: 'Sistema',
      importance: 'Alta',
      status: 'En progreso',
      assigneeId: 'UCG-IT-014',
      slaHours: slaFor('Alta'),
      assetId: null,
      tags: ['salesforce', 'emas-interface', 'recurrente', 'customer-id-mismatch'],
      createdAt: day(6),
      updatedAt: day(1),
      cliente: sampleClientes['CY2526'],
      salesforceTxIds: ['3731'],
      errorMessage: 'Salesforce Customer ID is "001TQ00000kGWSrYAO", Shipto ID is "a03TQ00000k2rTxYAI". Salesforce indicates it is EMAS Customer Number "CY2526". ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match',
      recurrenceCount: 6,
      firstOccurrence: day(6),
      lastOccurrence: day(1),
      relatedKb: ['KB-029'],
      comments: [
        { author: 'P. Rivas',  authorId: 'EMP-2098',   role: 'empleado', type: 'message', body: 'Cliente CY2526 lleva 6 días reportando que no le procesa la facturación. Es de Yauco. Tienen evento mañana y necesitan resolver hoy.', createdAt: day(6) },
        { author: 'R. Quiles', authorId: 'UCG-IT-014', role: 'it',       type: 'message', body: 'Recibido. Aplicando la solución de KB-029 (re-mapeo de Customer ID). Te confirmo en 2h.', createdAt: day(5) },
      ],
    },
    {
      id: 'SM-00042',
      summary: 'Customer ID mismatch · RO1858 · ship-to 01 y 02 fallan',
      description: 'Panadería El Trigo (RO1858) tiene 2 ship-tos en EMAS pero ambos fallan la validación con SF. Customer ID coincide pero ship-to no se enlaza correctamente.',
      empleadoId: 'EMP-1881',
      categoria: 'Sistema',
      importance: 'Media',
      status: 'Recibido',
      assigneeId: null,
      slaHours: slaFor('Media'),
      assetId: null,
      tags: ['salesforce', 'emas-interface', 'recurrente', 'ship-to'],
      createdAt: hr(3),
      updatedAt: hr(3),
      cliente: sampleClientes['RO1858'],
      salesforceTxIds: ['3732', '3733'],
      errorMessage: 'Salesforce Customer ID is "0013t00001zftHPAAY", Shipto ID is "a03TQ00000Dp3HCYAZ". Salesforce indicates it is EMAS Customer Number "RO1858", Ship-To "01". ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match',
      recurrenceCount: 5,
      firstOccurrence: day(8),
      lastOccurrence: hr(3),
      relatedKb: ['KB-029'],
      comments: [
        { author: 'R. Lozada', authorId: 'EMP-1881', role: 'empleado', type: 'message', body: 'Panadería El Trigo (RO1858) no procesa órdenes de ninguna de sus 2 sucursales (ship-to 01 y 02). Pasa desde la semana pasada.', createdAt: hr(3) },
      ],
    },
    {
      id: 'SM-00041',
      summary: 'Related EMAS Customer Does Not Exist · TX 3735, 3736',
      description: 'Cliente nuevo (Carlos Méndez) creado en Salesforce pero no se replicó a EMAS. Las transacciones 3735 y 3736 fueron rechazadas por que el EMAS Customer no existe.',
      empleadoId: 'EMP-1755',
      categoria: 'Sistema',
      importance: 'Media',
      status: 'En progreso',
      assigneeId: 'UCG-IT-009',
      slaHours: slaFor('Media'),
      assetId: null,
      tags: ['salesforce', 'emas-interface', 'cliente-nuevo'],
      createdAt: day(2),
      updatedAt: hr(18),
      cliente: sampleClientes['NOEMAS'],
      salesforceTxIds: ['3735', '3736'],
      errorMessage: 'Salesforce Sends Customer ShipTo Transaction # 3735, Salesforce Customer ID is "001TQ00000qHlnqYAC", Shipto ID is "a03TQ00000pPvTxYAK". ERROR: *** Related EMAS Customer Does Not Exist.',
      recurrenceCount: 2,
      relatedKb: ['KB-031'],
      comments: [
        { author: 'D. Soto',   authorId: 'EMP-1755',   role: 'empleado', type: 'message', body: 'Cliente Carlos Méndez se creó en Salesforce esta mañana pero las transacciones de él dan error. Parece que no se sincronizó con EMAS.', createdAt: day(2) },
        { author: 'C. Méndez', authorId: 'UCG-IT-009', role: 'it',       type: 'note',    body: 'Confirmado: el job de replicación SF→EMAS estaba detenido entre 7am-8am hoy. Voy a forzar la sincronización del registro.', createdAt: day(2) },
      ],
    },
    {
      id: 'SM-00040',
      summary: 'Customer ID mismatch · RO3852 (Hotel Costa Sol)',
      description: 'Hotel Costa Sol (RO3852) en Maunabo. SF y EMAS dan mismatch en TX 3737 y 3738.',
      empleadoId: 'EMP-2042',
      categoria: 'Sistema',
      importance: 'Media',
      status: 'En progreso',
      assigneeId: 'UCG-IT-007',
      slaHours: slaFor('Media'),
      assetId: null,
      tags: ['salesforce', 'emas-interface', 'customer-id-mismatch'],
      createdAt: day(1),
      updatedAt: hr(6),
      cliente: sampleClientes['RO3852'],
      salesforceTxIds: ['3737', '3738'],
      errorMessage: 'Salesforce Sends Customer ShipTo Transaction # 3737, Salesforce Customer ID is "001TQ00000SFKskYAH", Shipto ID is "a03TQ00000SEewoYAD". Salesforce indicates it is EMAS Customer Number "RO3852". ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match',
      recurrenceCount: 4,
      relatedKb: ['KB-029'],
      comments: [
        { author: 'E. Núñez',   authorId: 'EMP-2042',   role: 'empleado', type: 'message', body: 'Hotel Costa Sol (RO3852) tiene este error desde ayer. Es cuenta grande, ya escalé al gerente.', createdAt: day(1) },
        { author: 'J. Marrero', authorId: 'UCG-IT-007', role: 'it',       type: 'message', body: 'Recibido. Mismo patrón que RO4822. Aplicando KB-029.', createdAt: hr(20) },
      ],
    },

    // ===== Other realistic situations =====
    {
      id: 'SM-00039',
      summary: 'Reset de contraseña SSO',
      empleadoId: 'EMP-2098',
      categoria: 'Acceso',
      importance: 'Baja',
      status: 'Resuelto',
      assigneeId: 'UCG-IT-021',
      slaHours: slaFor('Baja'),
      tags: ['sso', 'password'],
      createdAt: hr(5),
      updatedAt: hr(4.2),
      comments: [
        { author: 'P. Rivas',   authorId: 'EMP-2098',   role: 'empleado', type: 'message', body: 'Mi contraseña expiró y no me deja entrar a Salesforce.', createdAt: hr(5) },
        { author: 'L. Rivera',  authorId: 'UCG-IT-021', role: 'it',       type: 'message', body: 'Listo. Te envié contraseña temporal por correo. Expira en 24h.', createdAt: hr(4.2) },
      ],
    },
    {
      id: 'SM-00038',
      summary: 'VPN se desconecta cada 10 min',
      empleadoId: 'EMP-2104',
      categoria: 'Red',
      importance: 'Media',
      status: 'En progreso',
      assigneeId: 'UCG-IT-014',
      slaHours: slaFor('Media'),
      tags: ['vpn', 'red'],
      createdAt: hr(6),
      updatedAt: hr(2),
      comments: [],
    },
    {
      id: 'SM-00037',
      summary: 'Excel se traba con archivos de cierre mensual',
      empleadoId: 'EMP-1755',
      categoria: 'Software',
      importance: 'Baja',
      status: 'En progreso',
      assigneeId: 'UCG-IT-009',
      slaHours: slaFor('Baja'),
      tags: ['excel', 'finanzas'],
      createdAt: hr(10),
      updatedAt: hr(4),
      comments: [],
    },
    {
      id: 'SM-00036',
      summary: 'Teclado no responde · Logitech K380',
      empleadoId: 'EMP-1981',
      categoria: 'Hardware',
      importance: 'Baja',
      status: 'Resuelto',
      assigneeId: 'UCG-IT-018',
      slaHours: slaFor('Baja'),
      tags: ['hardware'],
      createdAt: day(1),
      updatedAt: hr(20),
      comments: [],
    },
    {
      id: 'SM-00035',
      summary: 'Acceso a carpeta compartida bloqueado',
      empleadoId: 'EMP-2042',
      categoria: 'Acceso',
      importance: 'Media',
      status: 'En progreso',
      assigneeId: 'UCG-IT-014',
      slaHours: slaFor('Media'),
      createdAt: day(1.2),
      updatedAt: hr(18),
      comments: [],
    },
    {
      id: 'SM-00034',
      summary: 'Pantalla parpadea intermitentemente',
      empleadoId: 'EMP-1981',
      categoria: 'Hardware',
      importance: 'Media',
      status: 'Resuelto',
      assigneeId: 'UCG-IT-021',
      slaHours: slaFor('Media'),
      createdAt: day(1.4),
      updatedAt: day(1),
      comments: [],
    },
    {
      id: 'SM-00033',
      summary: 'Lentitud al abrir Power BI',
      empleadoId: 'EMP-2098',
      categoria: 'Sistema',
      importance: 'Baja',
      status: 'Cerrado',
      assigneeId: 'UCG-IT-009',
      slaHours: slaFor('Baja'),
      createdAt: day(2),
      updatedAt: day(1.5),
      comments: [],
    },
    {
      id: 'SM-00032',
      summary: 'Customer ID mismatch · RO4822 (anterior — resuelto temporalmente)',
      empleadoId: 'EMP-2104',
      categoria: 'Sistema',
      importance: 'Alta',
      status: 'Cerrado',
      assigneeId: 'UCG-IT-007',
      slaHours: slaFor('Alta'),
      tags: ['salesforce', 'emas-interface'],
      cliente: sampleClientes['RO4822'],
      salesforceTxIds: ['3725', '3726'],
      errorMessage: 'ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match',
      createdAt: day(20),
      updatedAt: day(13),
      comments: [
        { author: 'J. Marrero', authorId: 'UCG-IT-007', role: 'it', type: 'message', body: 'Resuelto temporalmente con re-sync manual. Pero el problema raíz no se atacó — esperamos vuelva.', createdAt: day(13) },
      ],
    },
  ];

  const kb = [
    {
      id: 'KB-029',
      title: 'Resolución: Salesforce Customer ID y EMAS Customer Number Do Not Match',
      categoria: 'Sistema · Salesforce↔EMAS',
      uses: 53,
      sintomas: 'La interfaz SF→EMAS rechaza transacciones recurrentes para uno o más clientes. El log muestra: "ERROR: *** Salesforce Customer ID and EMAS Customer Number Do Not Match". El job programado no procesa estos clientes y las transacciones se descartan automáticamente a los 7 días.',
      causa: 'Hay tres causas conocidas: (1) Ship-To en Salesforce no coincide con el Ship-To configurado en EMAS para el mismo customer; (2) el Customer ID en Salesforce fue actualizado pero el mapeo en EMAS quedó desincronizado; (3) registro duplicado en EMAS donde solo uno tiene el ship-to correcto.',
      solucion: [
        'Verificar el Customer ID y Ship-To en Salesforce (campo "EMAS Customer Number" del registro).',
        'Verificar en EMAS que el Customer Number existe con el mismo Ship-To (suele ser 00, 01, 02 según número de sucursales del cliente).',
        'Si Ship-To no coincide: actualizar EMAS o Salesforce para que coincidan. Tropigas Admin tiene autoridad para corregir el lado SF.',
        'Si Customer ID no coincide: ejecutar `EXEC sp_resync_emas_customer @sfId = "<SF-ID>"` desde la consola de UCG-DB.',
        'Re-procesar las transacciones pendientes con: `EXEC sp_reprocess_pending @customerId = "<EMAS-ID>"`.',
        'Confirmar resolución re-corriendo el job manualmente y validando 0 errores en la cola.',
      ],
      prevencion: 'Auditoría semanal del mapeo SF↔EMAS. Cualquier cambio en Salesforce Customer ID debe notificarse al equipo UCG para validación cruzada.',
      relatedTickets: ['SM-00043', 'SM-00044', 'SM-00042', 'SM-00040', 'SM-00032'],
    },
    {
      id: 'KB-031',
      title: 'Resolución: Related EMAS Customer Does Not Exist',
      categoria: 'Sistema · Salesforce↔EMAS',
      uses: 12,
      sintomas: 'Transacciones rechazadas con: "ERROR: *** Related EMAS Customer Does Not Exist". Típicamente ocurre con clientes recién creados.',
      causa: 'El cliente fue creado en Salesforce pero el job de replicación SF→EMAS estaba detenido o falló para ese registro específico.',
      solucion: [
        'Verificar el estado del job de replicación: `SELECT * FROM emas_replication_jobs ORDER BY started_at DESC`.',
        'Si el último run falló: revisar el error log y corregir.',
        'Forzar la replicación manual del cliente específico: `EXEC sp_replicate_customer @sfId = "<SF-ID>"`.',
        'Re-procesar las transacciones pendientes.',
      ],
      prevencion: 'Monitor automático que alerte si el job de replicación está detenido > 30 min.',
      relatedTickets: ['SM-00041'],
    },
    {
      id: 'KB-007',
      title: 'Reset de contraseña SSO',
      categoria: 'Acceso',
      uses: 24,
      sintomas: 'Empleado no puede ingresar a Salesforce/EMAS/Outlook. Mensaje "Cuenta bloqueada" o "Password expirado".',
      causa: 'Password expirado por política (90 días) o cuenta bloqueada por intentos fallidos.',
      solucion: [
        'Verificar identidad del empleado por extensión interna o supervisor.',
        'Active Directory → Reset password → Generar password temporal (válida 24h).',
        'Enviar password al correo personal del empleado.',
        'Forzar cambio en próximo login.',
      ],
      prevencion: 'Notificación automática al empleado 7 días antes del expiración.',
      relatedTickets: ['SM-00039'],
    },
    {
      id: 'KB-022',
      title: 'VPN se desconecta intermitente',
      categoria: 'Red',
      uses: 6,
      sintomas: 'Pérdida de conexión cada 5-15 min en VPN.',
      causa: 'MTU mal configurado en cliente VPN.',
      solucion: ['Set MTU 1380 en cliente', 'Reconectar'],
      prevencion: 'Plantilla de instalación con MTU preconfigurado.',
      relatedTickets: ['SM-00038'],
    },
    {
      id: 'KB-018',
      title: 'Excel se traba con archivos grandes',
      categoria: 'Software',
      uses: 5,
      sintomas: 'Excel congela al abrir archivos > 50 MB (típicamente cierres mensuales).',
      causa: 'Falta de RAM, complementos antiguos, o archivos con macros pesadas.',
      solucion: ['Cerrar otras apps', 'Modo seguro: excel /safe', 'Deshabilitar add-ins', 'Sugerir Power BI para datasets grandes'],
      prevencion: 'Standardizar reportes pesados en Power BI.',
      relatedTickets: ['SM-00037'],
    },
    {
      id: 'KB-014',
      title: 'Reiniciar print server',
      categoria: 'Hardware',
      uses: 8,
      sintomas: 'No imprime desde ningún equipo de la sucursal.',
      causa: 'Spooler de Windows colgado.',
      solucion: ['Servicios → Print Spooler → Reiniciar', 'Limpiar cola si hay > 20 trabajos'],
      prevencion: 'Limpieza de cola semanal.',
      relatedTickets: [],
    },
  ];

  return {
    users,
    tickets,
    kb,
    counters: { lastTicketId: 44 },
    sampleClientes, // exposed for the form's customer search dropdown
  };
}

module.exports = { createInitialState };
